# Generated by Django 3.1.2 on 2020-10-11 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_auto_20201011_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.ForeignKey(limit_choices_to={'type': 'University'}, on_delete=django.db.models.deletion.PROTECT, to='bio.organization'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.ForeignKey(limit_choices_to={'type': 'Company'}, on_delete=django.db.models.deletion.PROTECT, to='bio.organization'),
        ),
    ]
