# Generated by Django 3.1.2 on 2020-10-11 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0003_auto_20201011_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bio.organization'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bio.organization'),
        ),
    ]
