# Generated by Django 3.1.2 on 2020-10-11 16:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0004_auto_20201011_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='details',
            field=tinymce.models.HTMLField(),
        ),
    ]
