# Generated by Django 3.1.2 on 2020-10-14 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0009_auto_20201014_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='bio.skill_type'),
        ),
    ]
