# Generated by Django 3.1.2 on 2020-10-18 22:57

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('bio', '0001_initial'), ('bio', '0002_auto_20201011_0033'), ('bio', '0003_auto_20201011_0038'), ('bio', '0004_auto_20201011_0053'), ('bio', '0005_auto_20201011_1202'), ('bio', '0006_auto_20201011_2050'), ('bio', '0007_auto_20201012_0029'), ('bio', '0008_auto_20201012_0111'), ('bio', '0009_auto_20201014_1936'), ('bio', '0010_auto_20201014_1948'), ('bio', '0011_auto_20201014_2158'), ('bio', '0012_auto_20201018_1854')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skill_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bio.organization_type')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('proficiency_level', models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=20, null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='bio.skill_type')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=40)),
                ('major', models.CharField(max_length=60)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('details', ckeditor_uploader.fields.RichTextUploadingField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bio.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('details', ckeditor_uploader.fields.RichTextUploadingField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bio.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('headline', models.CharField(max_length=100)),
                ('summary', ckeditor_uploader.fields.RichTextUploadingField()),
                ('profile_pic', models.ImageField(default='intro_pics/default_profile_pic.jpg', upload_to='intro_pics')),
                ('cover_pic', models.ImageField(null=True, upload_to='intro_pics')),
                ('facebook_url', models.URLField(blank=True, default='#', null=True)),
                ('github_url', models.URLField(blank=True, default='#', null=True)),
                ('instagram_url', models.URLField(blank=True, default='#', null=True)),
                ('linkedin_url', models.URLField(blank=True, default='#', null=True)),
                ('resume', models.FileField(null=True, upload_to='docs')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('details', ckeditor_uploader.fields.RichTextUploadingField()),
                ('type', models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Professional', 'Professional'), ('Independent', 'Independent'), ('Hobby', 'Hobby')], max_length=20, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bio.organization')),
            ],
        ),
    ]
