# Generated by Django 3.1.2 on 2020-10-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0008_auto_20201012_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency_level',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=20, null=True),
        ),
    ]
