# Generated by Django 3.1.2 on 2020-10-18 22:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0011_auto_20201014_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='intro',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
